trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    mkdir -p /var/www/html
    npm install
    npm run dev
  displayName: 'Install dependencies'
